- name: Deploy Docker to EC2
  run: |
    ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      cd ~/ml-api/telecom-churn-ml-api

      git pull origin main

      # Stop old container
      docker stop churn-container || true
      docker rm churn-container || true

      # Build new image
      docker build -t churn-api .

      # Run new container
      docker run -d -p 8000:8000 --name churn-container churn-api
    EOF
