name: Deploy to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy Docker to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/ml-api/telecom-churn-ml-api

            git pull origin main

            docker stop churn-container || true
            docker rm churn-container || true

            docker build -t churn-api .

            docker run -d -p 8000:8000 --name churn-container churn-api
          EOF
